# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

theme: jekyll-agency

url    : "teamnerf" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/ADA_Data_Story" # the subpath of your site, e.g. /blog

title      : The Climate of Climate Change
description: "A short data driven story on what is said and quoted in US politics on climate change. Who are the actors and what are they saying?"
author     : Team NERF
logo       : True

locale: "en-US"

collections:
  portfolio:

markdown: kramdown